myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('shirtserver/', include('shirtserver.urls')),
    path('admin/', admin.site.urls),
]

shirtserver/urls.py
from django.urls import path

from . import views

app_name = 'shirtserver'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name = 'detail'),
]

shirtserver/models.py
from django.db import models

class Shirt(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    pub_date = models.DateField()
    TYP = (
        ('M', 'M'),
        ('F', 'F'),
    )
    typ = models.CharField(max_length=1, choices=TYP)
    SIZE = (
        ('XS', 'XS'),
        ('S', 'S'),
        ('M', 'M'),
        ('L', 'L'),
        ('XL', 'XL'),
        ('XXL', 'XXL'),
        ('XXXL', 'XXXL'),
    )
    size = models.CharField(max_length=4, choices=SIZE)

    color = models.CharField(max_length=30, null = True)
    image = models.ImageField(upload_to='static/shirtserver/images/', verbose_name='image', null = True)

    def __str__(self):
        return self.name

shirtserver/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic

from .models import Shirt

class IndexView(generic.ListView):
    template_name = 'shirtserver/index.html'
    context_object_name = 'shirt_list'

    def get_queryset(self):
        return Shirt.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Shirt
    template_name = 'shirtserver/detail.html'

shirtserver/templates/shirtserver/detail.html
<h1>hhahah{{ s.name }}</h1>
<div class="detalji">

<p>datum objave: {{ s.pub_date }}</p>
<p>boja: {{s.color}}</p>
<p>velicina: {{s.size}}</p>
<p>tip: {{s.typ}}</p>
</div>

shirtserver/templates/shirtserver/index.html
{% load static%}

<h1>Boškove мајице</h1>

{% if shirt_list %}
    <ul>
    {% for s in shirt_list %}
        <li><a href="{% url 'shirtserver:detail' s.id %}">{{ s.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No shirt are available.</p>
{% endif %}